// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VulnManager.Infrastructure.Persistence;

#nullable disable

namespace VulnManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VulnManagerDbContext))]
    [Migration("20260927022455_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("acknowledged_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dedup_key");

                    b.Property<Guid?>("FindingId")
                        .HasColumnType("uuid")
                        .HasColumnName("finding_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("WebhookDeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("webhook_delivered_at");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("DedupKey")
                        .IsUnique()
                        .HasDatabaseName("ix_alerts_dedup_key");

                    b.HasIndex("FindingId")
                        .HasDatabaseName("ix_alerts_finding_id");

                    b.HasIndex("ProjectId", "AcknowledgedAt")
                        .HasDatabaseName("ix_alerts_project_id_acknowledged_at");

                    b.ToTable("alerts", null, t =>
                        {
                            t.HasCheckConstraint("ck_alerts_type", "type IN ('NEW_P1', 'NEW_KEV_MATCH', 'SLA_DUE_SOON', 'SLA_OVERDUE', 'FORENSIC_TRIAGE')");
                        });
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("actor_type");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_log_occurred_at");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_log_entity_type_entity_id");

                    b.ToTable("audit_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_log_actor_type", "actor_type IN ('USER', 'API_KEY', 'SYSTEM')");
                        });
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Namespace")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("namespace");

                    b.Property<string>("Purl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("purl");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset?>("VulnsCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vulns_checked_at");

                    b.HasKey("Id")
                        .HasName("pk_components");

                    b.HasIndex("Purl")
                        .IsUnique()
                        .HasDatabaseName("ix_components_purl");

                    b.HasIndex("VulnsCheckedAt")
                        .HasDatabaseName("ix_components_vulns_checked_at");

                    b.ToTable("components", (string)null);
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.ComponentVulnerability", b =>
                {
                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_id");

                    b.Property<Guid>("VulnerabilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("vulnerability_id");

                    b.Property<DateTimeOffset>("FirstMatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_matched_at");

                    b.Property<bool>("FixAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("fix_available");

                    b.PrimitiveCollection<string[]>("FixedVersions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("fixed_versions");

                    b.Property<DateTimeOffset>("LastMatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_matched_at");

                    b.Property<string>("SuggestedFixVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("suggested_fix_version");

                    b.HasKey("ComponentId", "VulnerabilityId")
                        .HasName("pk_component_vulnerabilities");

                    b.HasIndex("VulnerabilityId")
                        .HasDatabaseName("ix_component_vulnerabilities_vulnerability_id");

                    b.ToTable("component_vulnerabilities", (string)null);
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_id");

                    b.Property<Guid>("DetectedInImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("detected_in_import_id");

                    b.Property<DateTimeOffset>("FirstDetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_detected_at");

                    b.Property<bool>("ForensicTriageRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("forensic_triage_required");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("PriorityExplanation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("priority_explanation");

                    b.Property<string>("PriorityLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("priority_level");

                    b.Property<Guid?>("PriorityRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("priority_rule_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<DateOnly?>("RiskAcceptedUntil")
                        .HasColumnType("date")
                        .HasColumnName("risk_accepted_until");

                    b.Property<int?>("SlaDays")
                        .HasColumnType("integer")
                        .HasColumnName("sla_days");

                    b.Property<DateTimeOffset?>("SlaDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_due_at");

                    b.Property<string>("SlaExplanation")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("sla_explanation");

                    b.Property<string>("SlaPolicy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sla_policy");

                    b.Property<int?>("SlaRow")
                        .HasColumnType("integer")
                        .HasColumnName("sla_row");

                    b.Property<DateTimeOffset>("SlaStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("status_reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("VexStatementId")
                        .HasColumnType("uuid")
                        .HasColumnName("vex_statement_id");

                    b.Property<Guid>("VulnerabilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("vulnerability_id");

                    b.HasKey("Id")
                        .HasName("pk_findings");

                    b.HasIndex("ComponentId")
                        .HasDatabaseName("ix_findings_component_id");

                    b.HasIndex("DetectedInImportId")
                        .HasDatabaseName("ix_findings_detected_in_import_id");

                    b.HasIndex("PriorityRuleId")
                        .HasDatabaseName("ix_findings_priority_rule_id");

                    b.HasIndex("SlaDueAt")
                        .HasDatabaseName("ix_findings_sla_due_at")
                        .HasFilter("status = 'NEW'");

                    b.HasIndex("VexStatementId")
                        .HasDatabaseName("ix_findings_vex_statement_id");

                    b.HasIndex("VulnerabilityId")
                        .HasDatabaseName("ix_findings_vulnerability_id");

                    b.HasIndex("ProjectId", "ComponentId", "VulnerabilityId")
                        .IsUnique()
                        .HasDatabaseName("ix_findings_project_id_component_id_vulnerability_id");

                    b.HasIndex("ProjectId", "Status", "PriorityLevel")
                        .HasDatabaseName("ix_findings_project_id_status_priority_level");

                    b.ToTable("findings", null, t =>
                        {
                            t.HasCheckConstraint("ck_findings_accepted_until", "status <> 'ACCEPTED' OR risk_accepted_until IS NOT NULL");

                            t.HasCheckConstraint("ck_findings_not_affected_vex", "status <> 'NOT_AFFECTED' OR vex_statement_id IS NOT NULL");

                            t.HasCheckConstraint("ck_findings_priority_level", "priority_level IN ('P1', 'P2', 'P3', 'P4')");

                            t.HasCheckConstraint("ck_findings_sla_policy", "sla_policy IN ('BOD2604', 'SEVERITY')");

                            t.HasCheckConstraint("ck_findings_sla_row", "sla_row IS NULL OR (sla_row BETWEEN 1 AND 16)");

                            t.HasCheckConstraint("ck_findings_status", "status IN ('NEW', 'ACCEPTED', 'MITIGATED', 'FALSE_POSITIVE', 'NOT_AFFECTED', 'FIXED')");
                        });
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.FindingStatusChange", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangeSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("change_source");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("changed_by");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid")
                        .HasColumnName("finding_id");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("from_status");

                    b.Property<string>("Justification")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("justification");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("to_status");

                    b.Property<Guid?>("VexStatementId")
                        .HasColumnType("uuid")
                        .HasColumnName("vex_statement_id");

                    b.HasKey("Id")
                        .HasName("pk_finding_status_history");

                    b.HasIndex("FindingId", "ChangedAt")
                        .HasDatabaseName("ix_finding_status_history_finding_id_changed_at");

                    b.ToTable("finding_status_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_finding_status_history_from", "from_status IS NULL OR from_status IN ('NEW', 'ACCEPTED', 'MITIGATED', 'FALSE_POSITIVE', 'NOT_AFFECTED', 'FIXED')");

                            t.HasCheckConstraint("ck_finding_status_history_source", "change_source IN ('USER', 'SBOM_IMPORT', 'VEX', 'SYNC', 'EXPIRY')");

                            t.HasCheckConstraint("ck_finding_status_history_to", "to_status IN ('NEW', 'ACCEPTED', 'MITIGATED', 'FALSE_POSITIVE', 'NOT_AFFECTED', 'FIXED')");
                        });
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.KevEntry", b =>
                {
                    b.Property<string>("CveId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cve_id");

                    b.Property<string>("CatalogVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("catalog_version");

                    b.PrimitiveCollection<string[]>("Cwes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("cwes");

                    b.Property<DateOnly>("DateAdded")
                        .HasColumnType("date")
                        .HasColumnName("date_added");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<bool?>("ForensicTriage")
                        .HasColumnType("boolean")
                        .HasColumnName("forensic_triage");

                    b.Property<bool>("KnownRansomwareCampaignUse")
                        .HasColumnType("boolean")
                        .HasColumnName("known_ransomware_campaign_use");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("RequiredAction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("required_action");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_description");

                    b.Property<string>("VendorProject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vendor_project");

                    b.Property<string>("VulnerabilityName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("vulnerability_name");

                    b.HasKey("CveId")
                        .HasName("pk_kev_entries");

                    b.ToTable("kev_entries", (string)null);
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.PriorityRuleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<decimal>("EpssPercentileThreshold")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("epss_percentile_threshold");

                    b.Property<int?>("FixOnUpgradeDays")
                        .HasColumnType("integer")
                        .HasColumnName("fix_on_upgrade_days");

                    b.Property<decimal>("HighImpactMinCvss")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("high_impact_min_cvss");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rules");

                    b.Property<string>("SlaPolicy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sla_policy");

                    b.Property<string>("SlaSeverityDays")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("sla_severity_days");

                    b.Property<bool>("SsvcActiveCountsAsExploited")
                        .HasColumnType("boolean")
                        .HasColumnName("ssvc_active_counts_as_exploited");

                    b.Property<string>("UnknownSeverityAs")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unknown_severity_as");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_priority_rules");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("ix_priority_rules_is_active")
                        .HasFilter("is_active");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("ix_priority_rules_version");

                    b.ToTable("priority_rules", null, t =>
                        {
                            t.HasCheckConstraint("ck_priority_rules_epss_threshold", "epss_percentile_threshold > 0 AND epss_percentile_threshold <= 1");

                            t.HasCheckConstraint("ck_priority_rules_high_impact", "high_impact_min_cvss >= 0 AND high_impact_min_cvss <= 10");

                            t.HasCheckConstraint("ck_priority_rules_sla_policy", "sla_policy IN ('BOD2604', 'SEVERITY')");

                            t.HasCheckConstraint("ck_priority_rules_unknown", "unknown_severity_as IN ('LOW', 'HIGH')");
                        });
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("asset_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentSbomImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_sbom_import_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("environment");

                    b.Property<string>("Exposure")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("exposure");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("repository_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("CurrentSbomImportId")
                        .HasDatabaseName("ix_projects_current_sbom_import_id");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("ck_projects_asset_type", "asset_type IN ('APPLICATION', 'SERVER', 'NETWORK_DEVICE')");

                            t.HasCheckConstraint("ck_projects_environment", "environment IN ('PRODUCTION', 'DEVELOPMENT')");

                            t.HasCheckConstraint("ck_projects_exposure", "exposure IN ('INTERNAL', 'PUBLIC')");

                            t.HasCheckConstraint("ck_projects_repository_url", "repository_url IS NULL OR repository_url LIKE 'https://%'");
                        });
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.ProjectApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("KeyHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character(8)")
                        .HasColumnName("key_prefix")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id")
                        .HasName("pk_project_api_keys");

                    b.HasIndex("KeyPrefix")
                        .IsUnique()
                        .HasDatabaseName("ix_project_api_keys_key_prefix");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_api_keys_project_id");

                    b.ToTable("project_api_keys", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_api_keys_hash_length", "octet_length(key_hash) = 32");
                        });
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.SbomComponent", b =>
                {
                    b.Property<Guid>("SbomImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("sbom_import_id");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_id");

                    b.Property<string>("BomRef")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("bom_ref");

                    b.Property<string>("Scope")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scope");

                    b.HasKey("SbomImportId", "ComponentId")
                        .HasName("pk_sbom_components");

                    b.HasIndex("ComponentId")
                        .HasDatabaseName("ix_sbom_components_component_id");

                    b.ToTable("sbom_components", null, t =>
                        {
                            t.HasCheckConstraint("ck_sbom_components_scope", "scope IS NULL OR scope IN ('required', 'optional', 'excluded')");
                        });
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.SbomImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BomSerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bom_serial_number");

                    b.Property<int?>("BomVersion")
                        .HasColumnType("integer")
                        .HasColumnName("bom_version");

                    b.Property<int>("ComponentCount")
                        .HasColumnType("integer")
                        .HasColumnName("component_count");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("format");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("ImportedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("imported_by");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("sha256")
                        .IsFixedLength();

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer")
                        .HasColumnName("skipped_count");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("source_ref");

                    b.Property<string>("SpecVersion")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("spec_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sbom_imports");

                    b.HasIndex("ProjectId", "Sha256")
                        .IsUnique()
                        .HasDatabaseName("ix_sbom_imports_project_id_sha256");

                    b.ToTable("sbom_imports", null, t =>
                        {
                            t.HasCheckConstraint("ck_sbom_imports_format", "format IN ('CYCLONEDX_JSON')");

                            t.HasCheckConstraint("ck_sbom_imports_sha256", "sha256 ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_sbom_imports_size", "size_bytes > 0 AND size_bytes <= 10485760");

                            t.HasCheckConstraint("ck_sbom_imports_source", "source IN ('API', 'UPLOAD')");

                            t.HasCheckConstraint("ck_sbom_imports_status", "status IN ('PENDING', 'PROCESSED', 'FAILED')");
                        });
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.SyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("HttpRequests")
                        .HasColumnType("integer")
                        .HasColumnName("http_requests");

                    b.Property<int>("HttpThrottled")
                        .HasColumnType("integer")
                        .HasColumnName("http_throttled");

                    b.Property<int>("ItemsRequested")
                        .HasColumnType("integer")
                        .HasColumnName("items_requested");

                    b.Property<int>("ItemsUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("items_updated");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("trigger");

                    b.Property<string>("Watermark")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("watermark");

                    b.HasKey("Id")
                        .HasName("pk_sync_runs");

                    b.HasIndex("Source")
                        .IsUnique()
                        .HasDatabaseName("ux_sync_runs_single_running")
                        .HasFilter("status = 'RUNNING'");

                    b.HasIndex("Source", "StartedAt")
                        .HasDatabaseName("ix_sync_runs_source_started_at");

                    b.ToTable("sync_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_sync_runs_source", "source IN ('OSV', 'KEV', 'EPSS', 'CVE', 'NVD')");

                            t.HasCheckConstraint("ck_sync_runs_status", "status IN ('RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', 'SKIPPED')");

                            t.HasCheckConstraint("ck_sync_runs_trigger", "trigger IN ('SCHEDULED', 'MANUAL', 'SBOM_IMPORT', 'STARTUP', 'EXTERNAL')");
                        });
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.VexStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionStatement")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("action_statement");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("author");

                    b.PrimitiveCollection<string[]>("CdxResponse")
                        .HasColumnType("text[]")
                        .HasColumnName("cdx_response");

                    b.Property<string>("CdxState")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cdx_state");

                    b.Property<string>("ComponentPurl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("component_purl");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImpactStatement")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("impact_statement");

                    b.Property<string>("Justification")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("justification");

                    b.Property<string>("JustificationScheme")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("justification_scheme");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("revoked_by");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_import_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("VulnerabilityRef")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vulnerability_ref");

                    b.HasKey("Id")
                        .HasName("pk_vex_statements");

                    b.HasIndex("SourceImportId")
                        .HasDatabaseName("ix_vex_statements_source_import_id");

                    b.HasIndex("ProjectId", "VulnerabilityRef")
                        .HasDatabaseName("ix_vex_statements_project_id_vulnerability_ref")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("vex_statements", null, t =>
                        {
                            t.HasCheckConstraint("ck_vex_statements_affected", "status <> 'AFFECTED' OR action_statement IS NOT NULL");

                            t.HasCheckConstraint("ck_vex_statements_justification", "justification IS NULL OR (justification_scheme = 'CISA' AND justification IN ('component_not_present', 'vulnerable_code_not_present', 'vulnerable_code_not_in_execute_path', 'vulnerable_code_cannot_be_controlled_by_adversary', 'inline_mitigations_already_exist')) OR (justification_scheme = 'CYCLONE_DX' AND justification IN ('code_not_present', 'code_not_reachable', 'requires_configuration', 'requires_dependency', 'requires_environment', 'protected_by_compiler', 'protected_at_runtime', 'protected_at_perimeter', 'protected_by_mitigating_control'))");

                            t.HasCheckConstraint("ck_vex_statements_not_affected", "status <> 'NOT_AFFECTED' OR justification IS NOT NULL OR impact_statement IS NOT NULL");

                            t.HasCheckConstraint("ck_vex_statements_source", "source IN ('MANUAL', 'CYCLONE_DX_VEX')");

                            t.HasCheckConstraint("ck_vex_statements_status", "status IN ('NOT_AFFECTED', 'AFFECTED', 'FIXED', 'UNDER_INVESTIGATION')");
                        });
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.Vulnerability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Aliases")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("aliases");

                    b.Property<string>("CveId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cve_id");

                    b.Property<DateTimeOffset?>("CveSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cve_synced_at");

                    b.Property<decimal?>("CvssScore")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)")
                        .HasColumnName("cvss_score");

                    b.Property<string>("CvssSource")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cvss_source");

                    b.Property<string>("CvssVector")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cvss_vector");

                    b.Property<string>("CvssVersion")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("cvss_version");

                    b.Property<string>("Details")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("details");

                    b.Property<DateOnly?>("EpssDate")
                        .HasColumnType("date")
                        .HasColumnName("epss_date");

                    b.Property<decimal?>("EpssPercentile")
                        .HasPrecision(6, 5)
                        .HasColumnType("numeric(6,5)")
                        .HasColumnName("epss_percentile");

                    b.Property<decimal?>("EpssScore")
                        .HasPrecision(6, 5)
                        .HasColumnType("numeric(6,5)")
                        .HasColumnName("epss_score");

                    b.Property<DateTimeOffset?>("EpssSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("epss_synced_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_id");

                    b.Property<bool>("InKev")
                        .HasColumnType("boolean")
                        .HasColumnName("in_kev");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<DateTimeOffset?>("NvdSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("nvd_synced_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<bool?>("SsvcAutomatable")
                        .HasColumnType("boolean")
                        .HasColumnName("ssvc_automatable");

                    b.Property<string>("SsvcExploitation")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ssvc_exploitation");

                    b.Property<string>("SsvcTechnicalImpact")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ssvc_technical_impact");

                    b.Property<string>("Summary")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id")
                        .HasName("pk_vulnerabilities");

                    b.HasIndex("Aliases")
                        .HasDatabaseName("ix_vulnerabilities_aliases");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Aliases"), "gin");

                    b.HasIndex("CveId")
                        .HasDatabaseName("ix_vulnerabilities_cve_id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_vulnerabilities_external_id");

                    b.ToTable("vulnerabilities", null, t =>
                        {
                            t.HasCheckConstraint("ck_vulnerabilities_cve_id", "cve_id IS NULL OR cve_id ~ '^CVE-[0-9]{4}-[0-9]{4,}$'");

                            t.HasCheckConstraint("ck_vulnerabilities_cvss_score", "cvss_score IS NULL OR (cvss_score >= 0 AND cvss_score <= 10)");

                            t.HasCheckConstraint("ck_vulnerabilities_cvss_source", "cvss_source IS NULL OR cvss_source IN ('OSV', 'CNA', 'NVD')");

                            t.HasCheckConstraint("ck_vulnerabilities_cvss_version", "cvss_version IS NULL OR cvss_version IN ('3.0', '3.1', '4.0')");

                            t.HasCheckConstraint("ck_vulnerabilities_epss_percentile", "epss_percentile IS NULL OR (epss_percentile >= 0 AND epss_percentile <= 1)");

                            t.HasCheckConstraint("ck_vulnerabilities_epss_score", "epss_score IS NULL OR (epss_score >= 0 AND epss_score <= 1)");

                            t.HasCheckConstraint("ck_vulnerabilities_severity", "severity IN ('UNKNOWN', 'NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')");

                            t.HasCheckConstraint("ck_vulnerabilities_source", "source IN ('OSV')");

                            t.HasCheckConstraint("ck_vulnerabilities_ssvc_exploitation", "ssvc_exploitation IS NULL OR ssvc_exploitation IN ('NONE', 'POC', 'ACTIVE')");

                            t.HasCheckConstraint("ck_vulnerabilities_ssvc_technical_impact", "ssvc_technical_impact IS NULL OR ssvc_technical_impact IN ('PARTIAL', 'TOTAL')");
                        });
                });

            modelBuilder.Entity("VulnManager.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VulnManager.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VulnManager.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("VulnManager.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VulnManager.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.Alert", b =>
                {
                    b.HasOne("VulnManager.Domain.Entities.Finding", null)
                        .WithMany()
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_alerts_findings_finding_id");

                    b.HasOne("VulnManager.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_projects_project_id");
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.ComponentVulnerability", b =>
                {
                    b.HasOne("VulnManager.Domain.Entities.Component", null)
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_component_vulnerabilities_components_component_id");

                    b.HasOne("VulnManager.Domain.Entities.Vulnerability", null)
                        .WithMany()
                        .HasForeignKey("VulnerabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_component_vulnerabilities_vulnerabilities_vulnerability_id");
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.Finding", b =>
                {
                    b.HasOne("VulnManager.Domain.Entities.Component", null)
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_findings_components_component_id");

                    b.HasOne("VulnManager.Domain.Entities.SbomImport", null)
                        .WithMany()
                        .HasForeignKey("DetectedInImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_findings_sbom_imports_detected_in_import_id");

                    b.HasOne("VulnManager.Domain.Entities.PriorityRuleVersion", null)
                        .WithMany()
                        .HasForeignKey("PriorityRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_findings_priority_rules_priority_rule_id");

                    b.HasOne("VulnManager.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_findings_projects_project_id");

                    b.HasOne("VulnManager.Domain.Entities.VexStatement", null)
                        .WithMany()
                        .HasForeignKey("VexStatementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_findings_vex_statements_vex_statement_id");

                    b.HasOne("VulnManager.Domain.Entities.Vulnerability", null)
                        .WithMany()
                        .HasForeignKey("VulnerabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_findings_vulnerabilities_vulnerability_id");
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.FindingStatusChange", b =>
                {
                    b.HasOne("VulnManager.Domain.Entities.Finding", null)
                        .WithMany("History")
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_finding_status_history_findings_finding_id");
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.Project", b =>
                {
                    b.HasOne("VulnManager.Domain.Entities.SbomImport", null)
                        .WithMany()
                        .HasForeignKey("CurrentSbomImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_projects_sbom_imports_current_sbom_import_id");
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.ProjectApiKey", b =>
                {
                    b.HasOne("VulnManager.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_api_keys_projects_project_id");
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.SbomComponent", b =>
                {
                    b.HasOne("VulnManager.Domain.Entities.Component", null)
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sbom_components_components_component_id");

                    b.HasOne("VulnManager.Domain.Entities.SbomImport", null)
                        .WithMany("Components")
                        .HasForeignKey("SbomImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sbom_components_sbom_imports_sbom_import_id");
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.SbomImport", b =>
                {
                    b.HasOne("VulnManager.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sbom_imports_projects_project_id");
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.VexStatement", b =>
                {
                    b.HasOne("VulnManager.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vex_statements_projects_project_id");

                    b.HasOne("VulnManager.Domain.Entities.SbomImport", null)
                        .WithMany()
                        .HasForeignKey("SourceImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vex_statements_sbom_imports_source_import_id");
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.Finding", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("VulnManager.Domain.Entities.SbomImport", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
